name: Functional tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit:
    runs-on: code
    steps:
      - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - run: tox -e unit
  linux:
    runs-on: functional
    steps:
      - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - run: sudo tox -e py36,py310
  openbsd:
    runs-on: OpenBSD
    steps:
      - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - run: /home/github/openbsd_runner.sh
