name: Main CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linter:
    runs-on: code
    steps:
      - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - run: make nox session=linter python=python3.8
  repo:
    runs-on: code
    steps:
      - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - run: make nox session=repo python=python3.8
  unit:
    runs-on: code
    steps:
      - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - run: make nox session=unit python=python3.8
  neutron:
    runs-on: code
    steps:
      - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - run: make nox session=neutron python=python3.8
  linux-fedora-35:
    runs-on: linux-fedora-35
    steps:
      - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - run: sudo make nox session=linux-3.6
      - run: sudo make nox session=linux-3.10
  linux-ubuntu-18:
    runs-on: linux-ubuntu-18
    steps:
      - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - run: sudo make nox session=linux-3.6 python=python3.6
      - run: sudo make nox session=linux-3.10 python=python3.6
  openbsd:
    runs-on: OpenBSD
    steps:
      - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - run: /home/github/openbsd_runner.sh
