name: Functional tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: functional
    steps:
      - uses: actions/checkout@v3
      - run: sudo tox -e py38,py39,py310
