name: Main CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linter:
    runs-on: code
    steps:
      - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - run: tox -e linter
  unit:
    runs-on: code
    steps:
      - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - run: tox -e unit
  linux-fedora-35:
    runs-on: linux-fedora-35
    steps:
      - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - run: sudo tox -e py36,py310
  linux-ubuntu-18:
    runs-on: linux-ubuntu-18
    steps:
      - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - run: sudo tox -e py38
  openbsd:
    runs-on: OpenBSD
    steps:
      - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - run: /home/github/openbsd_runner.sh
