name: Code quality

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: code
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: pip install pre-commit
      - run: pre-commit run -a
